{"name": "test_02", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'data'", "trace": "self = <test_request.Test_case object at 0x000001C049977470>\nconn_qianhouzhi = None\n\n    def test_02(self,conn_qianhouzhi):\n        url = \"http://172.16.0.181:8508/pwrApi/infoscreen/pdeScreen/list\"\n        data = {\n            \"projectId\":\"2c92808e80f408230180f4a9e28d04c8\"\n        }\n        headers = {\n            \"userToken\":\"3d42dfd2540171e3908fc9ba8d7291a6\",\n            \"Content-Type\":\"application/json; charset=UTF-8\"\n        }\n        rep02 = requests.get(url = url,params =  data,headers = headers)\n        print(rep02.text)\n        #正则表达式提取\n        Test_case.tiqu = re.search('\"oid\":\"(.*?)\"',rep02.text)[1]\n        print(Test_case.tiqu)\n        # print(\"我是\"+Test_case.tiqu+\"的\")\n        print(rep02.json())\n>       YamlUtil.write_extract_yaml({'data':rep02.json().data['oid']})\nE       AttributeError: 'dict' object has no attribute 'data'\n\ntestcases\\test_request.py:50: AttributeError"}, "start": 1653629820771, "stop": 1653629820902, "uuid": "1f2b3089-aaba-43ec-85b8-4f1ad0482db1", "historyId": "4d0a09f709ef7c26a84fbb17c6036076", "testCaseId": "57f246f05d1c599e5949f24a9728ed65", "fullName": "testcases.test_request.Test_case#test_02", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_request"}, {"name": "subSuite", "value": "Test_case"}, {"name": "host", "value": "weiqiangchen"}, {"name": "thread", "value": "6676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_request"}]}